### ISSUE TITLE
transfer data both ways.

### ISSUE THREAD

**Issue by davidroze** [seemk/WebUDP#10]
Hi,
i have tested the echo examples and its works perfectly!:)
can i use a generic sdp offer and answer on the client side? i know the public ip of the server so no signalling  is required , how can i implement this?
and how can i receive data and not just send / and support multiple connections (unique) ?

**Comment by seemk** [comment]
Hi,

I don't think you will be able to skip the signalling, as the SDP exchange is needed to get the handshake (STUN -> SCTP over DTLS) working. At least I don't think browsers will connect to the server without proper signalling. However, if you don't want to use HTTP for signalling and want to do something custom, you can check the interface at [Wu.h](https://github.com/seemk/WebUDP/blob/master/Wu.h), it's platform independent and at the moment there are 2 implementations using it (WuHostEpoll, WuHostNode).

I'm not sure if I understand your second question, so feel free to correct me: the server handles connections for you, you can support multiple connections by storing the ```WuClient``` pointers somewhere, passed to you inside the ```WuEvent``` struct defined at [Wu.h](https://github.com/seemk/WebUDP/blob/master/Wu.h)

Do you mean receiving data on the client side or server side?

**Comment by seemk** [comment]
Closing this since it has been over a month.
