### ISSUE TITLE
Using with SCTP

### ISSUE THREAD

**Issue by ClosetMonkey** [seemk/WebUDP#11]
I was drawn here because I'm looking for a UDP like solution for an HTML5 game, however after noticing WuSctp.h and doing some further code surfing I'm interested in possibly using the webudp in projects that require reliable packets as well. Is it possible to configure WebUDP to optionally use SCTP, and if so can you point me in the direction to figure it out? I'm out of time for now to do much more digging. Thanks

**Comment by seemk** [comment]
Hi!

Just to clarify a bit: WebRTC datachannels are always using SCTP, which itself is tunneled over UDP.

While it's possible to switch on reliable mode for conforming datachannel and SCTP implementations, I haven't added it to this project yet, it's only implementing a very small subset (just the unreliable part) of the SCTP protocol.

**Comment by need-sleep** [comment]
After some thought, I think the route your going is great. I can name a handful of reliable native webrtc datachannel libraries (not to mention building from chromium). Your the only one that tries to emulate UDP and your doing a great job at it. I didn't quit digging and I'm pretty confident that I can use WebUDP with a few existing network engines built over UDP such as ENet (https://github.com/lsalzman/enet). Many of these existing projects could be compiled using web assembly is it wasn't for the fact that Wasm uses websockets to emulate UDP, your route is much better. If one cuts out networking from ENet or similar engines and just uses their packet handling functions they can potentially be compiled for browsers for handling packets from WebUDP. I'll be up for days working through this. I'm sure you'll do great if you make it a more general purpose webrtc lib, but they already exist and some circles are crying for browser-based UDP.

**Comment by seemk** [comment]
Thanks, it should definitely be possible to use ENet as a backend for WebUDP. See [EchoServer.js](https://github.com/seemk/WebUDP/blob/master/examples/EchoServer.js), which is using node's UDP and HTTP servers. With ENet you would need a small HTTP server to do the SDP exchange as well.

Basically you would need to use these 3 functions at [Wu.h](https://github.com/seemk/WebUDP/blob/master/Wu.h):
```cpp
SDPResult WuExchangeSDP(Wu* wu, const char* sdp, int32_t length);
void WuHandleUDP(Wu* wu, const WuAddress* remote, const uint8_t* data,
                 int32_t length);
void WuSetUDPWriteFunction(Wu* wu, WuWriteFn write);
```
On the browser side, if ENet has write callbacks available, then you could just use these to write to WebUDP's JS interface, as in the following example, where I modified ioquake's networking code to talk over WebRTC:
https://github.com/seemk/ioq3/blob/master/code/qcommon/net_web.c#L266

**Comment by ClosetMonkey** [comment]
I'm thinking on a lower lever. For example,big you look at https://github.com/lsalzman/enet/blob/0eaf48eeb0d94a18d079378d8b76d588832ce838/unix.c#L431 you can see where WebUDP can be practically dropped in. It's event loop is practically the same used in WuHostEpoll.cpp as well.
