### ISSUE TITLE
make webUDP a lib not server.

### ISSUE THREAD

**Issue by notedit** [seemk/WebUDP#3]
make webUDP a lib not a server,  so we can binding to other language.

what do you think about this?

**Comment by notedit** [comment]
leave the signalling to the  application level.

**Comment by seemk** [comment]
That's an interesting idea! I agree that it's a bit too tied to epoll at the moment and I've been thinking of adding Windows support. Some kind of an input and output layer over the core library would be a sensible API. Maybe it would be okay to have 2 input functions to the library? One for signalling (TCP at the moment) and one for STUN and SCTP (UDP). So you could just give the library a bunch of packet memory, doesn't matter where it came from.

**Comment by notedit** [comment]
Yes, That is what i mean.

**Comment by seemk** [comment]
Just a heads up - I started working on this on the lib branch. Not compilable yet, but I'll let you know when it's in a working state.

**Comment by notedit** [comment]
thanks,  i will give a test.

**Comment by seemk** [comment]
I split the library into 2 parts now. The core is now platform independent and I wrote a node.js binding that uses it. See https://github.com/seemk/WebUDP/blob/lib/examples/webudp.js for a node.js based echo server. 

Will merge it to master in a few days, after I add the fuzz tests and additional documentation.

**Comment by seemk** [comment]
Merged it to master.

**Comment by notedit** [comment]
thanks  @seemk   i will give a try
