### ISSUE TITLE
Can you provide a client test example ?

### ISSUE THREAD

**Issue by lxlenovostar** [seemk/WebUDP#5]
I' m a new learner in JavaScript and WebRTC.  I want to test WebUDP, so can you provide a client test example in javascript. 

Thank you.

**Comment by seemk** [comment]
An example that connects to the echo server is available in the [js](https://github.com/seemk/WebUDP/tree/master/js) folder, ```wusocket.js``` is a wrapper around the WebRTC API, you can see its usage in ```roundtrip_histogram.html```. I will add a stripped down example when I get home later.

**Comment by seemk** [comment]
I've added a stripped down echo client to examples/client/simple_echo_client.html. Hope it's less confusing now.

ea809e2
