### ISSUE TITLE
EchoServer don't send "Server Hello" in DTLSv1.0

### ISSUE THREAD

**Issue by lxlenovostar** [seemk/WebUDP#7]
I have test simple_echo_client.html and wusocket.js.  

Test case 1:
In a ubuntu virtual machine. 
Browser client(chrome) and EchoServer are all on the ubuntu. This test pass.

Test case 2:
Browser client(chrome) in Window 7 (a network behind NAT)
EachoServer on server (have a public IP)
This don't work. I have compare packet bewteen Test case 1 and Test case 2.
In test case 2, EachoServer don're reply "Server Hello" in DTLSv1.0. EachoServer
print "EchoServer: client leave" after awhile

I just update simple_echo_client.html:
```
 //let socket = new WuSocket(window.location.protocol + "//" + window.location.hostname + ":" + PORT);
  //let socket = new WuSocket("http://101.69.114.92" + ":" + PORT);
  //let socket = new WuSocket("http://10.8.226.202" + ":" + PORT);
  let socket = new WuSocket("http://202.5.21.177" + ":" + PORT);
```

And I run EachoServer in this way:
`./EchoServer 202.5.21.177 9555`

This is bug? or I don't use in a right way?

Thank you.

**Comment by seemk** [comment]
Which Chrome version are you using? I reproduced your test case 2 (Chrome 63.0.3239 behind NAT, WebUDP on public IP on DigitalOcean's servers) and it worked.

Maybe your public server has port 9555 closed? I know that on AWS you explicitly have to open ports for incoming traffic.

**Comment by seemk** [comment]
Also check your browser's console when using simple_echo_client.html, is there anything there?

EchoServer executable doesn't print received messages, simple_echo_client.html only outputs the messages it receives with console.log.

**Comment by seemk** [comment]
Here's how the handshake looked for me through Wireshark, WebUDP is running on port 9424 here.

![image](https://user-images.githubusercontent.com/5329631/34557813-27d5b420-f144-11e7-93e0-6568e7487c41.png)

**Comment by lxlenovostar** [comment]
1. I use Chrome (63.0.3239.84),  chromium also don't work.
2.the log in Browser is:
```
received ice candidate
 RTCIceCandidate {candidate: "candidate:891687685 1 udp 2113937151 10.8.114.11 5… typ host generation 0 ufrag Alk4 network-cost 50", sdpMid: "data", sdpMLineIndex: 0}candidate: "candidate:891687685 1 udp 2113937151 10.8.114.11 58875 typ host generation 0 ufrag Alk4 network-cost 50"sdpMLineIndex: 0sdpMid: "data"__proto__: RTCIceCandidatecandidate: (...)sdpMLineIndex: (...)sdpMid: (...)toJSON: ƒ toJSON()constructor: ƒ RTCIceCandidate()Symbol(Symbol.toStringTag): "RTCIceCandidate"get candidate: ƒ ()set candidate: ƒ ()get sdpMLineIndex: ƒ ()set sdpMLineIndex: ƒ ()get sdpMid: ƒ ()set sdpMid: ƒ ()__proto__: Object
 add ice candidate success       wusocket.js:89
 all local candidates received     wusocket.js:37
```

**Comment by seemk** [comment]
I left my EchoServer running at ```http://188.166.46.128:9424``` if you want to try that.
Also http://188.166.46.128:8080/simple_echo_client.html

Will take it down later.

**Comment by seemk** [comment]
In your logs you receive only one RTCIceCandidate, when I connect I receive 2 of these. wusocket.js is currently using 1 external Google STUN server  ```stun:stun.l.google.com:19302``` (https://github.com/seemk/WebUDP/blob/master/examples/client/wusocket.js#L25-L27). Maybe that external Google STUN server could be causing troubles for you? I will test with an internal stun server only.

**Comment by seemk** [comment]
Ok I think I know now, for some reason  when I switch ```stun:stun.l.google.com:19302``` in wusocket.js with my own address ```stun:188.166.46.128:9424``` I get only a single RTCIceCandidate as well.

As a temporary workaround you could try with another STUN server in wusocket.js, e.g. ```"stun:stun.services.mozilla.com:3478"```. I will make it configurable soon.

**Comment by lxlenovostar** [comment]
1.I use other stun server(stun.ekiga.net:3478), so I can have 2 Candidates.
![_010418_070708_pm](https://user-images.githubusercontent.com/444868/34561210-df17be96-f183-11e7-8af7-ffacbc386fca.jpg)
But it still don't work.

**Comment by lxlenovostar** [comment]
2.I start server and get packets on server.
```
./EchoServer 101.69.114.92 33333

 tcpdump -i eth0 -w test.pcap tcp port 33333 or udp port 33333
```
The whole process is as follows:
![_010418_071319_pm](https://user-images.githubusercontent.com/444868/34561247-00a03e62-f184-11e7-8824-e317fd0fb216.jpg)

**Comment by lxlenovostar** [comment]
I add some log in Wu.cpp  .
![_010418_073355_pm](https://user-images.githubusercontent.com/444868/34561725-643f56d6-f186-11e7-860f-c264b490cde0.jpg)

When I run the EchoServer,  the message is:
![_010418_073613_pm](https://user-images.githubusercontent.com/444868/34561771-8b0f86d2-f186-11e7-9b79-55061ef8330f.jpg)

So I think EchoServer receive "Client Hello" and don't reply a "Server Hello".

Thank you.

**Comment by seemk** [comment]
Perhaps DTLS Server Hello is exceeding the MTU for you and it gets dropped.
Can you try adding debug statements to these lines to see how many bytes are being written, I think Server Hello should not exceed 1 KB and should fit a single packet:
https://github.com/seemk/WebUDP/blob/master/Wu.cpp#L401
https://github.com/seemk/WebUDP/blob/master/Wu.cpp#L197

**Comment by lxlenovostar** [comment]
I add more logs.
![_010418_074954_pm](https://user-images.githubusercontent.com/444868/34562249-7506b37c-f188-11e7-8f71-8d923c3b347f.jpg)



The messages is:
![_010418_074824_pm](https://user-images.githubusercontent.com/444868/34562182-3f3ba41e-f188-11e7-8774-265b76face20.jpg)

So I think the key line is:
**while (BIO_ctrl_pending(client->outBio) > 0)**

Thank you.

**Comment by seemk** [comment]
Thanks for extra info, I think the handshake might be going wrong here:
https://github.com/seemk/WebUDP/blob/master/Wu.cpp#L396-L399

Now if I could reproduce this somehow!

**Comment by seemk** [comment]
Which OpenSSL version are you using when you compiled WebUDP?
Does the demo link (https://www.vektor.space/webudprtt.html) work for you on Windows 7 or any other OS that you use?

I've tested this link on:
Linux (lubuntu) - Chrome, Firefox
macOS - Chrome, Firefox, Safari
Windows 10 - Chrome, Firefox

**Comment by seemk** [comment]
I managed to reproduce the case where the server is not sending DTLS Server Hello when I set OpenSSL's MTU to a very low value (100). Setting a higher MTU fixed it.

![image](https://user-images.githubusercontent.com/5329631/34585102-12233de2-f1a7-11e7-96ba-ba3cdbff7fa6.png)

Can you test with the latest version (f0ee147068bb6494cb4e6a6a3a1ac8bbef9d0eff)? Handshake error reporting should be improved now as well.

**Comment by lxlenovostar** [comment]
1.OpenSSL version is:
[root@bogon build]# rpm -qa | grep openssl
openssl-1.0.1e-57.el6.x86_64
openssl-devel-1.0.1e-57.el6.x86_64
openssl098e-0.9.8e-20.el6.centos.1.x86_64

2. I  get the latest version WebUDP, the issues is still exist.

Thank you.

**Comment by seemk** [comment]
Do you have the possibility to upgrade to OpenSSL 1.0.2n (I think this is the latest stable)? I've been using 1.0.2* versions myself.
In any case, I will try with openssl-1.0.1 in later today to see if this is causing issues.

**Comment by seemk** [comment]
Dropped support for OpenSSLs older than 1.0.2 in f894c98eaa93938070410b0dbf2ad4d6d4be9c75. I noticed that when Firefox started with a DTLS 1.2 Hello, but the server was forcing 1.0, Firefox ended the connection. I am not sure if it's related to your issue though.
https://www.vektor.space/webudprtt.html Does this link work for you on Windows 7? It's the latest version running on Ubuntu, compiled with OpenSSL 1.0.2g.

**Comment by lxlenovostar** [comment]
I use OpenSSL 1.0.2n in ubuntu, this is OK.  I can't use OpenSSL 1.0.2n on CentOS, because CentOS is 
Production Environment.
Thank you.
